### ISSUE TITLE
str({ devDefault: undefined }) generates an incorrect type

### ISSUE THREAD

**Issue by denis-sokolov** [af/envalid#201] opened 2023-01-05 16:11 UTC
`str({ devDefault: undefined })` is intended to return undefined in development, based on this existing test:

https://github.com/af/envalid/blob/53f54e94108b7d1eaadba59c9883b0b6f4318e54/tests/basics.test.ts#L53-L59

However, the type of the resulting value is reported as `string` instead of `string | undefined`.

**Comment by jsamr** [comment] 2023-01-05 18:39
^ Probably caused by https://github.com/af/envalid/pull/194, will take a look

**Comment by af** [comment] 2023-01-10 05:19
Should be fixed in 8.0.0-beta.1, please re-open otherwise!

**Closed by af** 2023-01-10 05:19 UTC
