### ISSUE TITLE
Unable to override NODE_ENV validation

### ISSUE THREAD

**Issue by virkt25** [af/envalid#97] opened 2019-02-15 21:53 UTC
I tried overriding the validation rules for `NODE_ENV` to support additional types by setting `choices` as follows:

```
{
  NODE_ENV: str({default: 'development', choices: ['production', 'development', 'test', 'staging']})
}
```

but when I actually set `NODE_ENV=staging`, I get the following error:

```
{ EnvError: Value "staging" not in choices [development,test,production]
```

**Comment by af** [comment] 2019-02-21 04:43
After tweaking the example in the repo with your custom NODE_ENV validator, I'm not able to reproduce, I don't see that error and am able to verify that `env.NODE_ENV` is being set to `staging`. Could you share more of your application where you're seeing the error?

**Comment by virkt25** [comment] 2019-02-25 15:34
Hi @af, thanks so much for looking into this! 

I tried to recreate the problem in a example repo and it was actually a bit challenging BUT I finally figured out what might be the issue. 

We are encapsulating `envalid` into a class, see the repo below. If the class is instantiated twice, then the error occurs ... otherwise everything works fine. Where we ran into the issue, the class was instantiated twice. 

I haven't figured out why it might be causing this issue but any help would be appreciated -- though I'm certain now it's not `envalid` and rather how I'm using it. 

Reproduction Repo: https://github.com/virkt25/envalid-test

**Comment by af** [comment] 2019-03-02 18:09
Hmm, nothing jumps out at me immediately there, maybe there is some state being shared between instances somehow? Or perhaps the `map` isn't being initialized correctly the second time, although that should be evident from the logging you have in place...

Going to close this since it's not an issue with the library

**Closed by af** 2019-03-02 18:09 UTC
